name: Deploy Github Pages

on:
  push:
    branches:
      - master
    paths:
      - 'docs/**'
jobs:
  page-deploy:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - uses: actions/checkout@v2
    - name: Use Node.js 15
      uses: actions/setup-node@v2
      with:
        node-version: 15
    - name: Use npm 7
      run: npm install -g npm@7
    - name: Install
      run: |
        npm ci
      env:
        CI: true
    - name: Build Document
      run: |
        npm run build:docs
    - name: Deploy to GitHub Pages
      if: success()
      uses: crazy-max/ghaction-github-pages@v2
      with:
        target_branch: gh-pages
        build_dir: docs/.vitepress/dist
        jekyll: false
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}