MODEL:
    name: "BMN"
    tscale: 200
    dscale: 200
    feat_dim: 2048
    prop_boundary_ratio: 0.5
    num_sample: 32
    num_sample_perbin: 3
    anno_file: "/home/work/datasets/EuroCup2016/input_for_bmn/label.json"
    feat_path: '/home/work/datasets/EuroCup2016/input_for_bmn/feature'

TRAIN:
    subset: "train"
    epoch: 20
    batch_size: 24
    num_threads: 8
    use_gpu: True
    num_gpus: 4
    learning_rate: 0.001
    learning_rate_decay: 0.1
    lr_decay_iter: 5000
    l2_weight_decay: 1e-4

VALID:
    subset: "validation"
    batch_size: 24
    num_threads: 8
    use_gpu: True
    num_gpus: 4

TEST:
    subset: "validation"
    batch_size: 1
    num_threads: 1
    snms_alpha: 0.001
    snms_t1: 0.5
    snms_t2: 0.9
    output_path: "/home/work/checkpoints/models_bmn/BMN_results"
    result_path: "/home/work/checkpoints/models_bmn/evaluate_results"

INFER:
    subset: "test"
    batch_size: 1
    num_threads: 1
    snms_alpha: 0.4
    snms_t1: 0.5
    snms_t2: 0.9
    filelist: 'data/dataset/bmn/infer.list'
    output_path: "data/output/INFER/BMN_results"
    result_path: "data/predict_resultsst"
