MODEL:
    name: "TSN"
    format: "pkl" # ["video", "frames", "pkl"]
    num_classes: 8      # 16
    seglen: 1
    image_mean: [0.485, 0.456, 0.406]
    image_std: [0.229, 0.224, 0.225]
    num_layers: 50      # 101
    topk: 5

TRAIN:
    seg_num: 7  # training with 3 segments
    epoch: 45
    short_size: 256
    target_size: 224
    num_reader_threads: 12
    buf_size: 1024
    batch_size: 72
    use_gpu: True
    num_gpus: 2
    filelist: "/home/work/datasets/EuroCup2016/input_for_tsn/train.list"
    learning_rate: 0.0002
    learning_rate_decay: 0.1
    l2_weight_decay: 1e-4
    momentum: 0.9
    total_videos: 7394      # 36287  # modify it according to the number samples of your dataset
   # use_dali: True

VALID:
    seg_num: 7
    short_size: 256
    target_size: 224
    num_reader_threads: 12
    buf_size: 1024
    batch_size: 48
    filelist: "/home/work/datasets/EuroCup2016/input_for_tsn/val.list"

TEST:
    seg_num: 9
    short_size: 256
    target_size: 224
    num_reader_threads: 12
    buf_size: 1024
    batch_size: 16
    filelist: "/home/work/datasets/EuroCup2016/input_for_tsn/val.list"

INFER:
    seg_num: 300  # infer using 300 segments
    short_size: 256
    target_size: 224
    num_reader_threads: 12
    buf_size: 1024
    batch_size: 1
    filelist: "/home/work/datasets/EuroCup2016/input_for_tsn/val.list"
    video_path: ""
    kinetics_labels: "/home/work/datasets/EuroCup2016/label.json"
