MODEL: #MODEL field
  framework: "Recognizer2D"
  backbone:
    name: "ResNet"
    depth: 101
  head:
    name: "TSNHead"
    num_classes: 3396 #Optional, not used in video_tag_tsn.
    in_channels: 2048 #input channel of the extracted feature.
    drop_ratio: 0. #the ratio of dropout
    std: 0.01 #std value in params initialization
    return_feature: True  #tsn is used to extract feature in video_tag

DATASET: #DATASET field
  test_batch_size: 1
  num_workers: 0 #Mandatory, XXX the number of subprocess on each GPU.
  test:
    format: "VideoDataset" #Mandatory, indicate the type of dataset, associate to the 'paddlevidel/loader/dateset'
    file_path: "data/video_tag/infer.list" #Mandatory, list of file path

PIPELINE: #PIPELINE field
  test:
    decode:
      name: "VideoDecoder"
    sample:
      name: "Sampler"
      valid_mode: True
      num_seg: 300
      seg_len: 1
    transform:
      - Scale:
          short_size: 256
      - CenterCrop:
          target_size: 224
      - Image2Array:
      - Normalization:
          mean: [0.485, 0.456, 0.406]
          std: [0.229, 0.224, 0.225]

model_name: "TSN"
