MODEL:                                              #MODEL field
  framework: "BMNLocalizer"
  backbone:
    name: "BMN"
    feat_dim: 2688
    tscale: 200
    dscale: 200
    prop_boundary_ratio: 0.5
    num_sample: 32
    num_sample_perbin: 3
  loss:
    name: "BMNLoss"
    tscale: 200
    dscale: 200

DATASET:                                            #DATASET field
  batch_size: 6                                     #single card bacth size
  test_batch_size: 1
  num_workers: 8
  train:
    format: "BMNDataset"
    file_path: "dataset/basketball/tsm_bmn_lstm/train/train_list/basketball_bmn_label.json"
    subset: "train"
  valid:
    format: "BMNDataset"
    file_path: "dataset/basketball/tsm_bmn_lstm/train/train_list/basketball_bmn_label.json"
    subset: "validation"
  test:
    format: "BMNDataset"
    test_mode: True
    file_path: "dataset/basketball/tsm_bmn_lstm/train/train_list/basketball_bmn_label.json"
    subset: "validation"

PIPELINE:                                           #PIPELINE field
  train:                                            #Mandotary, indicate the pipeline to deal data
    load_feat:
      name: "LoadFeat"
      feat_path: "dataset/basketball/tsm_bmn_lstm/data/basketball-20210622-200/input_for_bmn/feature/"
    transform:                                      #Mandotary, image transfrom operator
      - GetMatchMap:
          tscale: 200
      - GetVideoLabel:
          tscale: 200
          dscale: 200

  valid:                                            #Mandotary, indicate the pipeline to deal data
    load_feat:
      name: "LoadFeat"
      feat_path: "dataset/basketball/tsm_bmn_lstm/data/basketball-20210622-200/input_for_bmn/feature/"
    transform:                                      #Mandotary, image transfrom operator
      - GetMatchMap:
          tscale: 200
      - GetVideoLabel:
          tscale: 200
          dscale: 200

  test:                                             #Mandatory, indicate the pipeline to deal data
    load_feat:
      name: "LoadFeat"
      feat_path: "dataset/basketball/tsm_bmn_lstm/data/basketball-20210622-200/input_for_bmn/feature/"
    transform:                                      #Mandotary, image transfrom operator
      - GetMatchMap:
          tscale: 200
      - GetVideoLabel:
          tscale: 200
          dscale: 200

OPTIMIZER:                                          #OPTIMIZER field
  name: 'Adam'
  learning_rate:
    iter_step: True
    name: 'CustomPiecewiseDecay'
    boundaries: [8000]                     
    values: [0.001, 0.0001]
  weight_decay:
    name: 'L2'
    value: 1e-4

METRIC:
  name: 'BMNMetric'
  tscale: 200
  dscale: 200
  file_path: "data/dataset/bmn_data/activitynet_1.3_annotations.json"
  ground_truth_filename: "data/dataset/bmn_data/activity_net_1_3_new.json"
  subset: "validation"
  output_path: "data/bmn/BMN_Test_output"
  result_path: "data/bmn/BMN_Test_results"


INFERENCE:
  name: 'BMN_Inference_helper'
  feat_dim: 2688
  dscale: 200
  tscale: 200
  result_path: "data/bmn/BMN_INFERENCE_results"


model_name: BMN
epochs: 20                                          #Mandatory, total epoch
log_level: "INFO"
resume_from: ""                                     #checkpoint path.
