MODEL: #MODEL field
  framework: "RecognizerGCN" #Mandatory, indicate the type of network, associate to the 'paddlevideo/modeling/framework/' .
  backbone: #Mandatory, indicate the type of backbone, associate to the 'paddlevideo/modeling/backbones/' .
    name: "EfficientGCN"
    data_shape: [3, 6, 288, 25, 2]
    stem_channel: 64
    block_args: [[48,1,0.5],[24,1,0.5],[64,2,1],[128,2,1]]
    fusion_stage: 2
    act: swish
    att_type: stja
    layer_type: SG
    drop_prob: 0.25
    kernel_size: [5,2]
    scale_args: [1.2,1.35]
    expand_ratio: 0
    reduct_ratio: 2
    bias: True
    edge: True
    num_class: 60
    graph:
        dataset: "ntu"

DATASET: #DATASET field
    batch_size: 16 #Mandatory, bacth size
    num_workers: 4 #Mandatory, the number of subprocess on each GPU.
    test_batch_size: 1
    test_num_workers: 0
    train:
        format: "NTU_Feeder" #Mandatory, indicate the type of dataset, associate to the 'paddlevidel/loader/dateset'
        file_path: "NTU-RGB-D120/xsub/train_data.npy" #Mandatory, train data index file path
        label_path: "NTU-RGB-D120/xsub/train_label.pkl"
    valid:
        format: "NTU_Feeder" #Mandatory, indicate the type of dataset, associate to the 'paddlevidel/loader/dateset'
        file_path: "NTU-RGB-D120/xsub/val_data.npy" #Mandatory, valid data index file path
        label_path: "NTU-RGB-D120/xsub/val_label.pkl"
        test_mode: True
    test:
        format: "NTU_Feeder" #Mandatory, indicate the type of dataset, associate to the 'paddlevidel/loader/dateset'
        file_path: "NTU-RGB-D120/xsub/val_data.npy" #Mandatory, valid data index file path
        label_path: "NTU-RGB-D120/xsub/val_label.pkl"
        test_mode: True


PIPELINE: #PIPELINE field
  train: #Mandotary, indicate the pipeline to deal with the training data, associate to the 'paddlevideo/loader/pipelines/'
    sample:
      name: "AutoPadding"
      window_size: 300
    transform: #Mandotary, image transfrom operator
      - SkeletonNorm:
  test: #Mandotary, indicate the pipeline to deal with the training data, associate to the 'paddlevideo/loader/pipelines/'
    sample:
      name: "AutoPadding"
      window_size: 300
    transform: #Mandotary, image transfrom operator
      - SkeletonNorm:

OPTIMIZER:
  name: 'Momentum'
  momentum: 0.9
  learning_rate: 0.1
  learning_rate:
    iter_step: True
    name: 'CustomWarmupCosineDecay'   # LR class name
    max_epoch: 70                     # init args
    warmup_epochs: 10                 # init args

model_name: "EfficientGCN"
log_interval: 10 #Optional, the interal of logger, default:10
epochs: 50 #Mandatory, total epoch
save_interval: 10







