DATASET:
    batch_size: 1
    batch_nums: 10
    num_workers: 0
    quant:
        format: "FrameDataset"
        data_prefix: "../../data/k400/rawframes"
        file_path: "../../data/k400/val_small_frames.list"
        suffix: 'img_{:05}.jpg'

PIPELINE:
    quant:
        decode:
            name: "FrameDecoder"
        sample:
            name: "Sampler"
            num_seg: 8
            seg_len: 1
            valid_mode: True
        transform:
            - Scale:
                short_size: 256
            - CenterCrop:
                target_size: 224
            - Image2Array:
            - Normalization:
                mean: [0.485, 0.456, 0.406]
                std: [0.229, 0.224, 0.225]

inference_model_dir: "../../inference/ppTSM"
quant_output_dir: "../../inference/ppTSM/quant_model"

model_name: "ppTSM"
log_level: "INFO" #Optional, the logger level. default: "INFO"
