name: Validate

on:
  pull_request

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js 15
      uses: actions/setup-node@v2
      with:
        node-version: 15
    - name: Use npm 7
      run: npm install -g npm@7
    - name: Install
      run: |
        npm ci
    - name: Lint
      run: |
        npm run lint
    - name: Build
      run: |
        npm run build
        npm run build:docs

