USE_LOCAL_MAXIMA: False #use local maxima to extract key frames
USE_ONE_SECOND: True # extract one frame during one second
THRESHOLD: 0.95 # the threshold to accept the ocr result
smooth_window_length: 10
_COR: False #whether save coordinate
LANG: zh
dir: 'tools/frames/' #temporal dir to save frames
USE_VIDEO_TAG: True #whether use video_tag