MODEL: #MODEL field
    framework: "ASRF" #Mandatory, indicate the type of network, associate to the 'paddlevideo/modeling/framework/' .
    backbone: #Mandatory, indicate the type of backbone, associate to the 'paddlevideo/modeling/backbones/' .
        name: "ASRF" #Mandatory, The name of backbone.
        in_channel: 2048
        num_features: 64
        num_classes: 11
        num_stages: 4
        num_layers: 10
    head:
        name: "ASRFHead" #Mandatory, indicate the type of head, associate to the 'paddlevideo/modeling/heads'
        num_classes: 11
        num_features: 64
        num_stages: 4
        num_layers: 10
        num_stages_asb: 4
        num_stages_brb: 4
    loss:
        name: "ASRFLoss"
        lambda_bound_loss: 0.1
        num_classes: 11
        ce: True
        asl_focal: False
        tmse: False
        gstmse: True
        asl_weight: True
        ce_weight: 1.0
        focal_weight: 1.0
        tmse_weight: 0.15
        gstmse_weight: 1.0
        file_path: "./data/gtea/splits/train.split4.bundle" #Mandatory, train data index file path
        label_path: "./data/gtea/gt_arr"
        boundary_path: "./data/gtea/gt_boundary_arr"
    postprocessing_method: "refinement_with_boundary"
    boundary_threshold: 0.5


DATASET: #DATASET field
    batch_size: 1 #! Mandatory, bacth size， segmentation only support batch_size 1
    num_workers: 4 #Mandatory, the number of subprocess on each GPU.
    test_batch_size: 1
    test_num_workers: 0
    train:
        format: "ASRFDataset" #Mandatory, indicate the type of dataset, associate to the 'paddlevidel/loader/dateset'
        file_path: "./data/gtea/splits/train.split4.bundle" #Mandatory, train data index file path
        feature_path: "./data/gtea/features"
        label_path: "./data/gtea/gt_arr"
        boundary_path: "./data/gtea/gt_boundary_arr"
    valid:
        format: "ASRFDataset" #Mandatory, indicate the type of dataset, associate to the 'paddlevidel/loader/dateset'
        file_path: "./data/gtea/splits/test.split4.bundle" #Mandatory, valid data index file path
        feature_path: "./data/gtea/features"
        label_path: "./data/gtea/gt_arr"
        boundary_path: "./data/gtea/gt_boundary_arr"
    test:
        format: "ASRFDataset" #Mandatory, indicate the type of dataset, associate to the 'paddlevidel/loader/dateset'
        file_path: "./data/gtea/splits/test.split4.bundle" #Mandatory, test data index file path
        feature_path: "./data/gtea/features"
        label_path: "./data/gtea/gt_arr"
        boundary_path: "./data/gtea/gt_boundary_arr"

PIPELINE: #PIPELINE field
    train: #Mandotary, indicate the pipeline to deal with the training data, associate to the 'paddlevideo/loader/pipelines/'
        sample:
            name: "SegmentationSampler"
            sample_rate: 1
        #transform: #Mandotary, image transfrom operator

    valid: #Mandotary, indicate the pipeline to deal with the training data, associate to the 'paddlevideo/loader/pipelines/'
        sample:
            name: "SegmentationSampler"
            sample_rate: 1
        #transform: #Mandotary, image transfrom operator

    test: #Mandatory, indicate the pipeline to deal with the validing data. associate to the 'paddlevideo/loader/pipelines/'
        sample:
            name: "SegmentationSampler"
            sample_rate: 1
        #transform: #Mandotary, image transfrom operator


OPTIMIZER: #OPTIMIZER field
    name: 'Adam'
    learning_rate:
        name: 'PiecewiseDecay'
        boundaries: [50]
        values: [0.0005, 1]


METRIC:
    name: 'SegmentationMetric'
    overlap: [.1, .25, .5]
    actions_map_file_path: "./data/gtea/mapping.txt"


INFERENCE:
    name: 'ASRF_Inference_helper'
    num_channels: 2048
    actions_map_file_path: "./data/gtea/mapping.txt"
    postprocessing_method: "refinement_with_boundary"
    boundary_threshold: 0.5
    feature_path: "./data/gtea/features"


model_name: "ASRF"
log_interval: 10 #Optional, the interal of logger, default:10
epochs: 50 #Mandatory, total epoch
save_interval: 40
